# Generated by Django 5.2.5 on 2026-03-30 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the certificate template', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Description of the template')),
                ('template_file', models.FileField(help_text='Upload PDF template with placeholders like {{full_name}}, {{sex}}, etc.', upload_to='certificate_templates/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Certificate Template',
                'verbose_name_plural': 'Certificate Templates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filled_data', models.JSONField(help_text='JSON data containing all filled certificate fields')),
                ('output_file', models.FileField(help_text='Generated PDF certificate file', upload_to='generated_certificates/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_certificates', to='certificates.certificatetemplate')),
            ],
            options={
                'verbose_name': 'Generated Certificate',
                'verbose_name_plural': 'Generated Certificates',
                'ordering': ['-created_at'],
            },
        ),
    ]
