# Generated by Django 5.2.5 on 2026-03-30 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificatetemplate',
            name='template_file',
            field=models.FileField(help_text='Upload PDF template for manual field placement', upload_to='certificate_templates/'),
        ),
        migrations.CreateModel(
            name='EditableField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(help_text='Name of the field (e.g., full_name, sex, dob)', max_length=255)),
                ('x', models.FloatField(help_text='X coordinate in points')),
                ('y', models.FloatField(help_text='Y coordinate in points')),
                ('width', models.FloatField(help_text='Width of the text box in points')),
                ('height', models.FloatField(help_text='Height of the text box in points')),
                ('text', models.TextField(blank=True, default='', help_text='Text content for this field')),
                ('font_size', models.IntegerField(default=12, help_text='Font size in points')),
                ('font_name', models.CharField(default='Mangal.ttf', help_text='Font name for rendering', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editable_fields', to='certificates.certificatetemplate')),
            ],
            options={
                'verbose_name': 'Editable Field',
                'verbose_name_plural': 'Editable Fields',
                'ordering': ['field_name'],
            },
        ),
    ]
